### ISSUE TITLE
Diagnostics: error messages not shown.

### ISSUE THREAD

**Issue by MarcusE1W** [reasonml-editor/atom-ide-reason#1]
Hi.
I just installed ide-reason and atom-ide-ui to use it with Ocaml. Some of the functionality like autocompletion or hovering over a item to se the data-type works.

However I do not get the feedback from Diagnostics as shown in the demo gif.
Basically I can write what ever I want. No warnings or errors come up.
The diagnostics function in the atom-ide is turned on.

I am using atom-ide-ui 0.5.2; reason-ide 0.1.3; language-ocaml 1.9.5 and atom 1.21

Any help would be appreciated.

**Comment by zaaack** [comment]
atom-ide-ui's linter is a little outdated then atom-linter, and some linter package may not compatible with it. I have disabled it and using [linter](https://atom.io/packages/linter) package for a while, didn't notice it's not working with ocaml-language-server. You can try disable it and use [linter](https://atom.io/packages/linter) package, too. 

BTW, I have switched to [Fable](https://github.com/fable-compiler/Fable) and vs code now, I didn't test this package with Atom's newest version. You can open Atom's devtools panel to see the error message and which plugin cause the problem.

**Comment by MarcusE1W** [comment]
Works now. Thanks :-)
