### ISSUE TITLE
Custom toolchain path per project

### ISSUE THREAD

**Issue by alex35mil** [reasonml-editor/atom-ide-reason#13]
I mentioned it in #11 

This thing doesn't work atm b/c `readFileConf` always returns empty string (b/c `projectPath` is not passed). Anyway, w/ changes introduced in #11 I don't think it makes sense to keep it as-is (even fixed). We can convert it into configuration file based on OSL configuration format and pick it from either `package.json` or `ide-reason.json` or whatever. And it will override default Atom configuration. Thoughts?

/cc @chenglou @zaaack

**Comment by zaaack** [comment]
> We can convert it into configuration file based on OSL configuration format and pick it from either package.json or ide-reason.json or whatever. And it will override default Atom configuration.

Totally agree, sorry I forgot to mention, I'll look into this later when I have time to test your PR.

**Comment by alex35mil** [comment]
What about having `ide-reason.json` in `.atom/` directory of the project? Thus it’s consistent w/ vscode and doesn’t pollute root.

**Comment by zaaack** [comment]
> What about having ide-reason.json in .atom/ directory of the project? Thus it’s consistent w/ vscode and doesn’t pollute root.


@alexfedoseev Good advice, I'll take it. I think you can send an advice to atom's official repo to make this as an official recommendation for per project plugin configuration, it would make more sense if other plugins can follow the convention.

**Comment by zaaack** [comment]
Close for https://github.com/reasonml-editor/atom-ide-reason/pull/16
