### ISSUE TITLE
Interface files generator

### ISSUE THREAD

**Issue by alex35mil** [reasonml-editor/atom-ide-reason#14]
I prototyped interface files generator: https://cl.ly/pnsG
It’s going to be available in tree view context menu and in `re`/`ml` buffers.
Should I incorporate it into `atom-ide-reason` or publish as stand-alone package?
Personally, I incline to the former to avoid dependency hell but wonder what community thinks about it?

**Comment by alex35mil** [comment]
From conversation on Discord:

> @chenglou : @alex.fedoseev keep it in atom-ide-reason for now. We can abstract later

**Comment by alex35mil** [comment]
Cleaned up and pushed to GH: https://github.com/alexfedoseev/atom-reason-interface-generator
Can either publish as stand-alone package or wait for `atom-ide-reason` update and inject it here.

**Comment by zaaack** [comment]
Hi, this is great, could you send a PR for this ?

**Comment by alex35mil** [comment]
@zaaack Yeah, I will transfer this to `atom-ide-reason`. I was waiting for dev branch to be merged and I need to learn some TS lol.

**Comment by alex35mil** [comment]
#20
