### ISSUE TITLE
Not in atom package list (yet)

### ISSUE THREAD

**Issue by MarcusE1W** [reasonml-editor/atom-ide-reason#2]
Hi
I can't find this updated package in the atpm package manager.
Has this been published already?

**Comment by zaaack** [comment]
Sorry for my late. Seems apm cannot figure out the right repo after changing the git repo, I republished a new version in the old repo and it should be the newest now. Thanks for your feedback!

**Comment by MarcusE1W** [comment]
Thanks, I just saw it. Will the old packe still be migrated into this one in the longer run ?

**Comment by zaaack** [comment]
Yes, I only updated the old repo for a work around, this one is the only official repo.

**Comment by MarcusE1W** [comment]
Ok, maybe it is just a question of updating links. When I search in Atom I get ide-reason in version 0.1.6 with owner reasonml-editor. Same thing on the atom.io side gives me owner zaaack.
When I click on the ide-reason package in Atom I get your zaaack page. 
That's why I was not sure which package it is that get's installed in Atom. Your package (as in Zaaack) or the reasonml-editor one.

**Comment by zaaack** [comment]
@MarcusE1W apm won't change repository url automatically, it can be either done by github's `transfer ownership` or update the database manually, I asked for help in [this thread](https://discuss.atom.io/t/cant-publish-after-changing-repository-in-package-json/30807/16), if it won't work I guess I should delete this repo and create a new one by `transfer ownership`.
