### ISSUE TITLE
Getting opaque error while running bsb on save

### ISSUE THREAD

**Issue by johnhaley81** [reasonml-editor/atom-ide-reason#40]
Using RLS with "Run bsb on save" I'm getting an error that doesn't tell me what's going on:

![image](https://user-images.githubusercontent.com/867780/50831629-b9d63480-1308-11e9-8ff6-5f77fc0ed6c1.png)

This is (probably?) a RLS issue but the display issue is (probably?) related to the plugin.

**Comment by zaaack** [comment]
@johnhaley81 Did you try running `./node_modules/.bin/bsb -version` in your project root? Looks you didn't install(link) bs-platform in your project.

**Comment by johnhaley81** [comment]
Thanks for getting back so fast @zaaack !

So it looks like I did a `yarn add <package>` which apparently corrupted my `bsb`? After I nuked `node_modules` and reinstall the packages it worked. So really this isn't an issue with either package :)

The only real actionable thing here is probably a better error message but that error message might be "Don't use yarn" :(

**Comment by alex35mil** [comment]
FWIW this should be fixed in `bs-platform@4.0.17`
