### ISSUE TITLE
$OCAMLLIB': -c: line 0: unexpected EOF while looking for matching `'' $OCAMLLIB': -c: line 1: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by Et7f3** [reasonml-editor/atom-ide-reason#46]
Hello,

I try to use ide-reason with atom but can't correctly.

step to reproduce:
![image](https://user-images.githubusercontent.com/29592775/56382187-1bb30e00-6217-11e9-870f-8e57bb1de3d8.png)
click 👆
close atom
open cmd.exe as administrator
travel to my directory and execute `atom .`

![image](https://user-images.githubusercontent.com/29592775/56382056-c840c000-6216-11e9-90cf-025090442987.png)

Ok so it don't work

I have tried `esy atom.cmd .`

![image](https://user-images.githubusercontent.com/29592775/56382825-9b8da800-6218-11e9-8448-e6ec4058a1f1.png)

they are text hidden:
`Unix.Unix_error(_, "opendir", "")Raised by primitive operation at file "unix.ml", line 360, characters 32-73 Called from file "util/Files.re", line 185, characters 9-28 Called from file "src/analyze/State.re", line 445, characters 4-58 Called from file "list.ml", line 88, characters 20-23 Called from file "src/analyze/State.re", line 442, characters 26-446 Called from file "src/analyze/State.re", line 602, characters 24-75 Called from file "src/lsp/NotificationHandlers.re", line 74, characters 24-72 Called from file "src/lsp/BasicServer.re", line 84, characters 11-35`

**Comment by zaaack** [comment]
Looks like windows problems, I haven't use ide-reason in windows, did you installed ocaml/reason environment via reason-cli?

**Comment by zaaack** [comment]
you can try with another language server in settings page:
![image](https://user-images.githubusercontent.com/5233940/56412371-751e4a00-62b6-11e9-8656-46944a2ed82e.png)

**Comment by Et7f3** [comment]
after changing language server
atom . => do nothing
![image](https://user-images.githubusercontent.com/29592775/56423773-fc1af480-62ad-11e9-8e48-dadfb32ca9ad.png)
and same for esy atom.cmd .
I have installed OCaml via esy packages.json
`"ocaml": "^4.7.0",` in dependencies
and when  I do esy ocaml I can execute ocaml so I think it correctly installed.
same of ocamlmerlin
copie of my web dev console
![image](https://user-images.githubusercontent.com/29592775/56432068-5dea5700-62cc-11e9-922b-580fcb23e06a.png)

**Comment by zaaack** [comment]
@Et7f3 I haven't use esy before, perhaps you can install ocaml in global environment. The errors comes from upstream projects, like reason-language-server and ocaml language server.

**Comment by Et7f3** [comment]
Yep the error was solve when reinstalling project 👍
