### ISSUE TITLE
Does not show type information for functions in ReasonReact

### ISSUE THREAD

**Issue by clouds56** [reasonml-editor/atom-ide-reason#5]
When I move my mouse to stringToElement in code `ReasonReact.stringToElement("hello")`, it just show `'a` instead of `(string) => 'a`, is it intended?
Or I'm missing something in configuration?

atom --version
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm list:
ide-reason@0.1.7
language-reason@0.0.4
language-ocaml@1.9.5
linter-refmt@0.3.1
linter-ocaml@1.2.0
ocaml-indent@0.6.1

Reason 3.0.3 @ 31f614c # refmt --version
2.0.0 # bsb -version
The OCaml toplevel, version 4.06.0 # ocaml --version

opam list:
merlin                          3.0.5
ocp-indent                      1.6.1
reason                          3.0.3

**Comment by clouds56** [comment]
I find out that this is a possible solution:

https://github.com/BuckleScript/bucklescript/blob/master/site/docsource/Installation.adoc
```
opam update
opam switch 4.02.3+buckle-master
opam install merlin reason
```

while I have to switch ocaml via opam every time **before** I open the atom, which is annoying.
Is it any chance to detect toolchain per project (e.g. specify ocaml environment in `.merlin` file)?

**Comment by zaaack** [comment]
Bucklescript/Reason can only work in a specific version of ocaml. I'm not sure currently there is a way to use different version of ocaml in different folder, maybe you can see merlin's document.

**Comment by clouds56** [comment]
Is it possible to use different PATH for different folder?
e.g. use `PATH=~/.opam/4.02.3+buckle-master/bin/:$PATH` for projects use reason while `PATH=~/.opam/master/bin/:$PATH` otherwise. Could the extension set different PATH before spawn ocaml-language-server/merlin?

**Comment by zaaack** [comment]
I think I can add a custom ocaml/merlin binary path setting, could you be sure this will work in your case? You can run atom with PATH env.

**Comment by clouds56** [comment]
Yes, it works.
While every time write PATH info in shell is annoying.

**Comment by zaaack** [comment]
@clouds56 v0.1.8 is published, you can prepend toolchain path to your path env per project either in `package.json` or a custom config file(`ide-reason.json`),

see: https://github.com/reasonml-editor/atom-ide-reason#custom-toolchain-path-per-project
  

Feel free to reopen this issue or create a new one if you still have problems.
