### ISSUE TITLE
IDE features hang

### ISSUE THREAD

**Issue by kgoggin** [reasonml-editor/atom-ide-reason#8]
The Reason IDE features seem to hang for me from the time I launch Atom. I'm not getting any context help in the code (squiggly lines, etc.), when I Cmd-click something I get the the spinning ball mouse cursor, and as soon as I save a .re file, the "Busy Signal" UI is constantly spinning, saying it's formatting whichever file I saved. The actual save/refmt does occur, though it takes a good 1-2s before it actually happens.

I ran into this when I first tried atom-ide a few weeks ago. Then in seemed to randomly start working for me, and it was great! Then it started hanging again a few days ago. It _may_ have been timed with me updating some of my Atom packages (I did a bulk update a few days ago, wish I'd paid closer attention to what they all were...).

I've tried restarting Atom, my terminal, and my whole machine but it's messed up each time I launch Atom. Here are some details about the current versions of things I'm running - please let me know if you need any more details:

Atom version: 1.23.3
atom-ide-reason version: 0.1.8
atom-ide-ui version: 0.7.1
Mac OSX 10.12.6

Thanks!

**Comment by lierdakil** [comment]
Problem description seems very similar to how #9 manifests.

**Comment by kgoggin** [comment]
Maybe? I did confirm today that I was able to recover from this by disabling the atom-ide-reason package, restarting Atom, and then re-enabling it. It also fixed itself after an update, but then it came back again the next time I quit and restarted Atom.

**Comment by zaaack** [comment]
I have published a new version v0.1.9 which fixed #9, I'm not sure this issue is related, but I guess you can have a try. 

Could you open Atom's dev tools and find the messages when Atom is hanging? You can enable atom-languageclient's debug log by runing `atom.config.set('core.debugLSP', true)` in Developer Tools Console.

**Comment by kgoggin** [comment]
@zaaack just updated and things _seem_ to be running more smoothly. Usually it'd hang after I restarted Atom but after a few tries everything is still good! I'll go ahead and close this for now, but if it pops back up I'll be sure to troubleshoot as you suggest and re-open with those details. Thanks! I so much prefer Atom to VSCode and writing Reason with this plugin is just amazing!

**Comment by scull7** [comment]
I'm not sure if this is related, but it seems that the code format tool is hanging.  
<img width="436" alt="screenshot 2018-03-10 16 02 29" src="https://user-images.githubusercontent.com/234352/37248069-97ba85ca-247c-11e8-8a25-57e37559486e.png">

I am using Atom v 1.24.1, ide-reason v 0.1.12, language-reason 0.0.4 and language-ocaml 1.9.5

Whenever I save a file it just keeps adding to the list of files it's "formatting".

**Comment by zaaack** [comment]
@scull7 Can you open atom's dev tools panel and paste the error message?

**Comment by scull7** [comment]
![screenshot 2018-03-10 22 12 04](https://user-images.githubusercontent.com/234352/37250381-1b5c496c-24b0-11e8-9ac8-27fc2f7487b1.png)

@zaaack I don't see any errors in the console.
