### ISSUE TITLE
Errors in PATH handling which break everything horribly

### ISSUE THREAD

**Issue by lierdakil** [reasonml-editor/atom-ide-reason#9]
https://github.com/reasonml-editor/atom-ide-reason/blob/07ec8b4292da7adc8adfe3570b8c3ce5a4b8ab86/lib/main.js#L20

should be 

```js
 joinEnvPath(...others) 
```
otherwise, an array gets converted to a string, `PATH` gets a spurious `,` at the beginning and everything breaks horribly.

Also, while on topic, why do you need `Object.create` in
https://github.com/reasonml-editor/atom-ide-reason/blob/07ec8b4292da7adc8adfe3570b8c3ce5a4b8ab86/lib/main.js#L54
?
I think it does more harm here, since suddenly `env` variables are not own properties, as those should be, but are prototype properties.

**Comment by zaaack** [comment]
Thanks! You are right, I guess I made many mistakes here. Thanks for letting me know.

Here are my changes, feel free to reopen this if there still have issues.
https://github.com/reasonml-editor/atom-ide-reason/blob/1d3a377d8931eb40923a90318122cf1694cf3a4c/lib/main.js#L9-L16

https://github.com/reasonml-editor/atom-ide-reason/blob/1d3a377d8931eb40923a90318122cf1694cf3a4c/lib/main.js#L49-L55
